In [ ]:
print("Hello Class of Artificial Intelligence ")

In [ ]:
n = int(input("Enter the number of rows you want to print? "))
for i in range(0, n):
    print()
    for j in range(0, i + 1):
        print("*", end="")

In [ ]:
table = 5
for i in range(10):
    print(f"{i} X {table} = {(i*table)}")
    
    
print(f"Data type table variable is : {type(table)}")

print(" ----------------- ")

table = "AI Class"

print(f"{table}")

print(f"Data type table variable is : {type(table)}")



In [ ]:
n = int(input("Enter the number: "))

numberInString = str(n)
sumOfDigits = int(0)
print(f"{type(numberInString)}")
for i in numberInString:    
    sumOfDigits = sumOfDigits + int(i)

print(f"Sum of digits are: {sumOfDigits}")

if(n%sumOfDigits == 0):
    print(f"Yes, {n} is a Harshad number.")
else:
    print(f"No, {n} is NOT a Harshad number.")



In [ ]:
a = 0
b=1
i=0
n=9
while(i<n):
    c = a+b
    a = b
    b = c
    i = i+1

print(f"{b}")


In [ ]:
a = [1,2,3,4,5,6,7,9,10]

b=1
i=2
x=0
while(a<10):
    x



In [1]:
inputNumber = input("Please enter the number for Table: ")

print(f"DataType of number: {type(inputNumber)}")

DataType of number: <class 'str'>


In [2]:
numberInint = int(inputNumber)

print(f"DataType of number: {type(numberInint)}")

DataType of number: <class 'int'>


In [3]:
for i in range(11):
    print(f"{numberInint} X {i}  = {(i*numberInint)}")
    
    
    

12 X 0  = 0
12 X 1  = 12
12 X 2  = 24
12 X 3  = 36
12 X 4  = 48
12 X 5  = 60
12 X 6  = 72
12 X 7  = 84
12 X 8  = 96
12 X 9  = 108
12 X 10  = 120


In [4]:
userNumber2 = input("Please enter the Number:: ")

print(f"{userNumber2} have datatype: {type(userNumber2)}")

13 have datatype: <class 'str'>


In [17]:
disc = {1:"first", 2:"second", 3:"Third", 4:"Four", 5:"Five", 6:"Six", 7:"Seven", 8:"Eight", 9:"Nine", 0:"Zero"}

for i in disc:
    print(f"{i} have value: {disc[i]}")

1 have value: first
2 have value: second
3 have value: Third
4 have value: Four
5 have value: Five
6 have value: Six
7 have value: Seven
8 have value: Eight
9 have value: Nine
0 have value: Zero


In [22]:
userNumber2 = input("Please enter the Number:: ")

output =""

for i in userNumber2:
    output = output + " "+ disc[int(i)]

print(f"{output}")

 first second Third Five Four Six Four Five Six Four


In [2]:
import cv2

image_path = "./binary_tree.png"
img = cv2.imread(image_path)

In [3]:
if img is None:
    print(f"Error: Could not load image from {image_path}")
else:
    print("Image loaded successfully.")
    # You can now work with the 'img' variable

Image loaded successfully.


In [4]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [5]:
type(img)

numpy.ndarray

In [7]:
img.shape

(731, 205, 3)

In [ ]:
A = np.array(str)

In [16]:
str = "Artificial-Intelligence"


In [18]:
print(str[2:19: 2])

tfca-nelg


In [19]:
import cv2

imagePath = "./binary_tree.png"

img = cv2.imread(imagePath)

In [20]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [21]:
img.shape

(731, 205, 3)

In [1]:
S = "Artificial Intelligence"

print(S[-7:-1])

ligenc


In [2]:
num = 5

for i in range(5, 1):
    print(f"{i} X {num} = {i*num}")

In [3]:
num = 5

for i in range(5, 1, -1):
    print(f"{i} X {num} = {i*num}")

5 X 5 = 25
4 X 5 = 20
3 X 5 = 15
2 X 5 = 10


In [18]:
import pandas as pd
df = pd.read_excel('CyS25 CISCO invitation.xlsx')


In [ ]:
df.columns
df.head(5)

df2= pd.DataFrame()

Sr #      Reg No                    Name
0     1  25-CyS-001    Hafiz Shehryar Ahmad
1     2  25-CyS-003         Jahan Zaib Khan
2     3  25-CyS-005  Muhammad Mujtaba Najam
3     4  25-CyS-006            Waleed Ahmed
4     5  25-CyS-007     Muhammad Ahmad Raza

In [16]:
df[['FirstName', 'SecondName']] = df['Name'].str.split(n=1, expand=True)


In [14]:
df['Email'] = df['Reg No'].str.lower() + '@student.hitecuni.edu.pk'


In [ ]:
df.to_excel('students_updated.xlsx', index=False)
