In [1]:
import numpy as np 
# Original 2D array 
arr = np.array([[0, 1], [2, 3]]) 
print("Original array:\n", arr) 
# Flatten the array 
flat_arr = arr.flatten() 
print("Flattened array:", flat_arr) 
# Find maximum and minimum values 
max_value = flat_arr.max() 
min_value = flat_arr.min() 
print("Maximum value of the flattened array:", max_value) 
print("Minimum value of the flattened array:", min_value)

Original array:
 [[0 1]
 [2 3]]
Flattened array: [0 1 2 3]
Maximum value of the flattened array: 3
Minimum value of the flattened array: 0


In [2]:
import numpy as np 
# Create 3x3 matrix with values from 2 to 10 
matrix = np.arange(2, 11).reshape(3, 3) 
print("3x3 Matrix with values from 2 to 10:") 
print(matrix)

3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
import numpy as np 
# Original integer array 
arr = np.array([1, 2, 3, 4]) 
print("Original array:", arr) 
# Convert array elements to float type 
float_arr = arr.astype(float) 
print("Array converted to float type:", float_arr) 

Original array: [1 2 3 4]
Array converted to float type: [1. 2. 3. 4.]


In [4]:
import numpy as np 
# Define two 2x2 matrices 
M1 = np.array([[1, 2], 
[0, 1]]) 
M2 = np.array([[1, 0], 
[2, 1]]) 
# Multiply the matrices 
result = np.dot(M1, M2) 
# Take the transpose of the resultant matrix 
transpose = np.transpose(result) 
print("Matrix M1:\n", M1) 
print("Matrix M2:\n", M2) 
print("Result of Multiplication:\n", result) 
print("Transpose of Resultant Matrix:\n", transpose)

Matrix M1:
 [[1 2]
 [0 1]]
Matrix M2:
 [[1 0]
 [2 1]]
Result of Multiplication:
 [[5 2]
 [2 1]]
Transpose of Resultant Matrix:
 [[5 2]
 [2 1]]


In [5]:
import numpy as np 
# Define the given matrix 
M = np.array([ 
[6, 1, 1, 3], 
[4, -2, 5, 1], 
[2, 8, 7, 6], 
[3, 1, 9, 7] 
]) 
# Calculate the inverse of the matrix 
inverse_M = np.linalg.inv(M) 
print("Original Matrix:\n", M) 
print("\nInverse of the Matrix:\n", inverse_M)

Original Matrix:
 [[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]

Inverse of the Matrix:
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
