In [1]:
import numpy as np

arr = np.array([[0, 1], [2, 3]])
print("Original flattened array:\n", arr)
print("Maximum value of the above flattened array:", arr.max())
print("Minimum value of the above flattened array:", arr.min())


Original flattened array:
 [[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [2]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values ranging from 2 to 10:")
print(matrix)


3x3 matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

float_arr = arr.astype(float)
print("Array converted to a float type:", float_arr)


Original array: [1 2 3 4]
Array converted to a float type: [1. 2. 3. 4.]


In [4]:
import numpy as np

M1 = np.array([[5, 5], [1, 2]])
M2 = np.array([[0, 1], [1, 0]])

result = np.dot(M1, M2)
transpose = result.T

print("Result of matrix multiplication:\n", result)
print("Transpose of the resultant matrix:\n", transpose)


Result of matrix multiplication:
 [[5 5]
 [2 1]]
Transpose of the resultant matrix:
 [[5 2]
 [5 1]]


In [5]:
import numpy as np

A = np.array([
    [6, 1, 1, 3],
    [4, -2, 5, 1],
    [2, 8, 7, 6],
    [3, 1, 9, 7]
], dtype=float)

A_inv = np.linalg.inv(A)
print("Inverse matrix:\n", np.round(A_inv, 8))


Inverse matrix:
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
