lab 03

In [44]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    fact = 1
    for i in range(2, n + 1):
        fact *= i
    return fact

num = 5
print("Factorial:", factorial(num))


Factorial: 120


In [45]:
def unique_list(lst):
    unique = []
    for item in lst:
        if item not in unique:
            unique.append(item)
    return unique

my_list = [1, 2, 2, 3, 4, 4, 5]
print("Unique List:", unique_list(my_list))


Unique List: [1, 2, 3, 4, 5]


In [46]:
def even_numbers(n):
    evens = []
    for i in range(1, n + 1):
        evens.append(i * 2)

    total_sum = sum(evens)
    product = 1
    for num in evens:
        product *= num

    return evens, total_sum, product

n = 5
even_list, s, p = even_numbers(n)

print("Even Numbers:", even_list)
print("Sum:", s)
print("Product:", p)


Even Numbers: [2, 4, 6, 8, 10]
Sum: 30
Product: 3840


In [47]:
def match_strings(str1, str2):
    if str1 == str2:
        return "Strings match"
    else:
        return "Strings do not match"

s1 = "hello"
s2 = "world"
print(match_strings(s1, s2))

s1 = "python"
s2 = "python"
print(match_strings(s1, s2))


Strings do not match
Strings match


In [49]:
def login(username, password):
    correct_user = "admin"
    correct_pass = "1234"

    if username == correct_user and password == correct_pass:
        return "Login Successfully"
    else:
        return "Invalid username or password"

u = input("Enter username: ")
p = input("Enter password: ")

print(login(u, p))


Login Successfully


# lab 04

In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = qaname
        self.age = age
class Job:
    def __init__(self, designation, salary):
        self.designation = designation
        self.salary = salary
class Employee(Person, Job):
    def __init__(self, name, age, designation, salary):
        Person.__init__(self, name, age)   
        Job.__init__(self, designation, salary)
    def display(self):
        print(f"Name       : {self.name}")
        print(f"Age        : {self.age}")
        print(f"Designation: {self.designation}")
        print(f"Salary     : {self.salary}")
e = Employee("Qurrat ul Ain", 20, "cyber security", 120000)
e.display()

Name       : Qurrat ul Ain
Age        : 20
Designation: cyber security
Salary     : 120000


In [35]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * (self.radius ** 2)

    def perimeter(self):
        return 2 * math.pi * self.radius

c = Circle(5)
print(f"Circle radius = {c.radius}")
print(f"Area           = {c.area():.4f}")
print(f"Perimeter      = {c.perimeter():.4f}")


Circle radius = 5
Area           = 78.5398
Perimeter      = 31.4159


In [38]:
def my_pow(x, n):
    if n == 0:
        return 1.0

    negative = n < 0
    n_abs = -n if negative else n
    result = 1.0
    base = x
    exp = n_abs

    while exp > 0:
        if exp % 2 == 1:
            result *= base
        base *= base
        exp //= 2

    return 1.0 / result if negative else result

# Test cases
print(my_pow(2, 3))    # Output: 8.0
print(my_pow(2, -3))   # Output: 0.125
print(my_pow(5, 0))    # Output: 1.0



8.0
0.125
1.0


In [40]:
class Item:
    def __init__(self, name, description, price):
        self.name = name
        self.description = description
        self.price = price

    def viewFullDescription(self):
        print(f"Name: {self.name}")
        print(f"Description: {self.description}")
        print(f"Price: {self.price}")

    def addToShoppingBasket(self):
        print(f"{self.name} added to shopping basket.")

    def removeFromShoppingBasket(self):
        print(f"{self.name} removed from shopping basket.")


class MP3(Item):
    def __init__(self, name, description, price, artist, duration):
        super().__init__(name, description, price)
        self.artist = artist
        self.duration = duration

    def play(self):
        print(f"Playing MP3: {self.name} by {self.artist}")

    def download(self):
        print(f"Downloading MP3: {self.name}")


class DVD(Item):
    def __init__(self, name, description, price, certificate, duration, actors):
        super().__init__(name, description, price)
        self.certificate = certificate
        self.duration = duration
        self.actors = actors

    def viewTrailer(self):
        print(f"Viewing trailer for DVD: {self.name}")


class Book(Item):
    def __init__(self, name, description, price, author, numberOfPages, genre):
        super().__init__(name, description, price)
        self.author = author
        self.numberOfPages = numberOfPages
        self.genre = genre

    def previewContent(self):
        print(f"Previewing content of book: {self.name}")


# ---------- Example Run ----------
if __name__ == "__main__":
    mp3 = MP3("Shape of You", "Popular song", 250, "Ed Sheeran", "4:24")
    dvd = DVD("Avengers: Endgame", "Action Movie", 1500, "PG-13", "3h 2m", ["Robert Downey Jr.", "Chris Evans"])
    book = Book("Python Basics", "Learn Python Programming", 900, "John Doe", 300, "Education")

    mp3.viewFullDescription()
    mp3.play()
    mp3.download()

    print("------")

    dvd.viewFullDescription()
    dvd.viewTrailer()

    print("------")

    book.viewFullDescription()
    book.previewContent()

    # Simple variables
    name = "Xiao Ming"
    age = 18
    print("Name:", name, "Age:", age)


Name: Shape of You
Description: Popular song
Price: 250
Playing MP3: Shape of You by Ed Sheeran
------
Name: Avengers: Endgame
Description: Action Movie
Price: 1500
Viewing trailer for DVD: Avengers: Endgame
------
Name: Python Basics
Description: Learn Python Programming
Price: 900
Previewing content of book: Python Basics
Name: Xiao Ming Age: 18


lab 05

In [23]:
import numpy as np

arr = np.array([[0, 1], [2, 3]])
print("Original flattened array:")
flat_arr = arr.flatten()
print("Flattened array:", flat_arr)
print("Maximum value of the above flattened array:", np.max(flat_arr))
print("Minimum value of the above flattened array:", np.min(flat_arr))


Original flattened array:
Flattened array: [0 1 2 3]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [24]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)
float_arr = arr.astype(float)
print("Array converted to a float type:", float_arr)


Original array: [1 2 3 4]
Array converted to a float type: [1. 2. 3. 4.]


In [26]:
import numpy as np

M1 = np.array([[1, 2], [0, 1]])
M2 = np.array([[2, 1], [1, 0]])
result = np.dot(M1, M2)
transpose = result.T
print("Matrix 1:", M1)
print("Matrix 2:", M2)
print("Result of multiplication:", result)
print("Transpose of result:", transpose)


Matrix 1: [[1 2]
 [0 1]]
Matrix 2: [[2 1]
 [1 0]]
Result of multiplication: [[4 1]
 [1 0]]
Transpose of result: [[4 1]
 [1 0]]


In [27]:
import numpy as np

A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])
inverse_A = np.linalg.inv(A)
print("Original Matrix:", A)
print("Inverse of Matrix:", inverse_A)


Original Matrix: [[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
Inverse of Matrix: [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


Lab 06 part a

In [43]:
import random
class Environment:
    def __init__(self):
        self.rooms = {'A': 'Dirty', 'B': 'Dirty', 'C': 'Dirty'}
        self.agent_location = 'A'
        self.clean_count = 0
    def get_percept(self):
        return self.agent_location, self.rooms[self.agent_location]
    def execute_action(self, action):
        if action == 'Vacuum':
            self.rooms[self.agent_location] = 'Clean'
            self.clean_count += 1
        elif action == 'Right':
            if self.agent_location == 'A':
                self.agent_location = 'B'
            elif self.agent_location == 'B':
                self.agent_location = 'C'
        elif action == 'Left':
            if self.agent_location == 'C':
                self.agent_location = 'B'
            elif self.agent_location == 'B':
                self.agent_location = 'A'
        elif action == 'RandomMove':
            self.agent_location = random.choice(['A', 'B', 'C'])
class SimpleReflexAgent:
    def __init__(self):
        self.rules = {
            ('A', 'Dirty'): 'Vacuum',
            ('B', 'Dirty'): 'Vacuum',
            ('C', 'Dirty'): 'Vacuum',
            ('A', 'Clean'): 'Right',
            ('B', 'Clean'): 'Right',
            ('C', 'Clean'): 'Left' }
    def select_action(self, percept, env):
        if all(status == 'Clean' for status in env.rooms.values()):
            return 'RandomMove'
        return self.rules.get(percept, 'NoOp')
env = Environment()
agent = SimpleReflexAgent()
for step in range(7):
    percept = env.get_percept()
    action = agent.select_action(percept, env)
    print(f"Step {step+1}: Percept: {percept}, Action: {action}")
    env.execute_action(action)
print(f"Rooms: {env.rooms}, Cleaned {env.clean_count} times\n")

Step 1: Percept: ('A', 'Dirty'), Action: Vacuum
Step 2: Percept: ('A', 'Clean'), Action: Right
Step 3: Percept: ('B', 'Dirty'), Action: Vacuum
Step 4: Percept: ('B', 'Clean'), Action: Right
Step 5: Percept: ('C', 'Dirty'), Action: Vacuum
Step 6: Percept: ('C', 'Clean'), Action: RandomMove
Step 7: Percept: ('C', 'Clean'), Action: RandomMove
Rooms: {'A': 'Clean', 'B': 'Clean', 'C': 'Clean'}, Cleaned 3 times



In [41]:
class SmartLightAgent:
    def __init__(self):
        pass

    def decide(self, presence, time_of_day):
        if presence and (6 <= time_of_day <= 18):
            return "Turn Off Light (Daytime)"
        elif presence and (time_of_day < 6 or time_of_day > 18):
            return "Turn On Light (Night)"
        else:
            return "Turn Off Light (No One Present)"

light_agent = SmartLightAgent()
print("--- Task 2: Smart Light System ---")
scenarios = [(True, 10), (True, 22), (False, 15)]
for presence, time_of_day in scenarios:
    action = light_agent.decide(presence, time_of_day)
    print(f"Presence={presence}, Time={time_of_day}:00 → Action: {action}")
print()


--- Task 2: Smart Light System ---
Presence=True, Time=10:00 → Action: Turn Off Light (Daytime)
Presence=True, Time=22:00 → Action: Turn On Light (Night)
Presence=False, Time=15:00 → Action: Turn Off Light (No One Present)



In [42]:
class ThermostatAgent:
    def __init__(self):
        self.memory = []

    def sense_and_act(self, temperature):
        self.memory.append(temperature)
        if len(self.memory) > 3:
            self.memory.pop(0)

        avg_temp = sum(self.memory) / len(self.memory)

        if avg_temp < 20:
            return "Turn On Heater"
        elif avg_temp > 24:
            return "Turn On Cooler"
        else:
            return "Maintain Temperature"

thermostat = ThermostatAgent()
temps = [19, 20, 23, 25, 22]
for t in temps:
    print(f"Temperature={t}°C → Action: {thermostat.sense_and_act(t)}")



Temperature=19°C → Action: Turn On Heater
Temperature=20°C → Action: Turn On Heater
Temperature=23°C → Action: Maintain Temperature
Temperature=25°C → Action: Maintain Temperature
Temperature=22°C → Action: Maintain Temperature


Lab 06

In [28]:
from collections import deque
graph1 = {
    0: [1, 2],
    1: [3, 4, 5],
    2: [5, 6],
    3: [],
    4: [],
    5: [],
    6: []
}
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    result = []

    while queue:
        node = queue.popleft()
        if node not in visited:
            result.append(node)
            visited.add(node)
            queue.extend(graph[node])
    return result
def dfs(graph, start):
    visited = set()
    stack = [start]
    result = []
    while stack:
        node = stack.pop()
        if node not in visited:
            result.append(node)
            visited.add(node)
            stack.extend(reversed(graph[node]))
    return result
print("BFS:", bfs(graph1, 0))
print("DFS:", dfs(graph1, 0))


BFS: [0, 1, 2, 3, 4, 5, 6]
DFS: [0, 1, 3, 4, 5, 2, 6]


In [29]:
graph = {
    'A': ['B', 'C'],
    'B': ['D'], 
    'C': ['E', 'I'], 
    'D': ['H'], 
    'E': ['H'], 
    'F': ['A', 'C'], 
    'G': [],    
    'H': ['J'],                                                                                                                                                      
    'I': ['G','J'],                                                                                                                    
    'J': ['G'] }
def dfs(graph, start):
    visited = set()
    order = []
    def dfs_helper(v):
        visited.add(v)
        order.append(v)
        for neighbor in graph[v]:
            if neighbor not in visited:
                dfs_helper(neighbor)
    dfs_helper(start)
    return order
from collections import deque
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    visited.add(start)
    order = []
    while queue:
        vertex = queue.popleft()
        order.append(vertex)
        for neighbor in graph[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)
    return order
dfs_order = dfs(graph, 'F')
bfs_order = bfs(graph, 'F')
print(f"DFS traversal starting from F:\nF {{ {', '.join(dfs_order)} }}")
print(f"BFS traversal starting from F:\nF {{ {', '.join(bfs_order)} }}")


DFS traversal starting from F:
F { F, A, B, D, H, J, G, C, E, I }
BFS traversal starting from F:
F { F, A, C, B, E, I, D, H, G, J }


lab 07

In [30]:
import heapq
from collections import deque
graph1 = {
    'a': ['b', 'c', 'd'],
    'b': ['c', 'e'],
    'c': ['e', 'f', 'd'],
    'd': ['f'],
    'e': ['z'],
    'f': ['z'],
    'z': []}
heuristic1 = {
    'a': 21,
    'b': 14,
    'c': 18,
    'd': 18,
    'e': 5,
    'f': 8,
    'z': 0}
def best_first(graph, h, start, goal):
    pq = []
    heapq.heappush(pq, (h[start], start))
    visited = set()
    parent = {start: None}
    while pq:
        _, node = heapq.heappop(pq)
        print("Visiting:", node)
        if node == goal:
            path = []
            while node:
                path.append(node)
                node = parent[node]
            return path[::-1]
        visited.add(node)
        for nb in graph[node]:
            if nb not in visited:
                heapq.heappush(pq, (h[nb], nb))
                parent[nb] = node
    return None
def beam_search(graph, h, start, goal, beam_width):
    queue = deque([[start]])
    while queue:
        candidates = []
        while queue:
            path = queue.popleft()
            node = path[-1]
            if node == goal:
                return path
            for nb in graph[node]:
                candidates.append((h[nb], path + [nb]))
        candidates.sort(key=lambda x: x[0])
        queue = deque([p for _, p in candidates[:beam_width]])
    return None
print("\n BEST FIRST SEARCH")
print(best_first(graph1, heuristic1, 'a', 'z'))
print("\n BEAM SEARCH ")
print(beam_search(graph1, heuristic1, 'a', 'z', beam_width=2))



 BEST FIRST SEARCH
Visiting: a
Visiting: b
Visiting: e
Visiting: z
['a', 'b', 'e', 'z']

 BEAM SEARCH 
['a', 'b', 'e', 'z']


In [31]:
import heapq
from collections import deque
graph2 = {
    'S': [('A',4), ('B',10), ('C',11)],
    'A': [('B',8), ('D',5)],
    'B': [('D',15)],
    'C': [('B',6), ('E',20), ('F',2)],
    'D': [('H',16), ('I',20), ('F',1)],
    'H': [('I',1), ('J',2)],
    'I': [('J',5), ('K',13), ('G',5)],
    'F': [('G',13)],
    'E': [('G',19)],
    'J': [('K',7)],
    'K': [('G',16)],
    'G': []}
heuristic2 = {
    'S': 7, 'A': 8, 'B': 6, 'C': 5, 'D': 5,
    'E': 3, 'F': 3, 'G': 0, 'H': 7, 'I': 4,
    'J': 5, 'K': 3}
def best_first2(graph, h, start, goal):
    pq = []
    heapq.heappush(pq, (h[start], start, [start]))
    visited = set()
    while pq:
        _, node, path = heapq.heappop(pq)
        print("Visiting:", node)
        if node == goal:
            return path
        visited.add(node)
        for nb, cost in graph[node]:
            if nb not in visited:
                heapq.heappush(pq, (h[nb], nb, path+[nb]))
    return None
def beam_search2(graph, h, start, goal, beam_width):
    queue = deque([[start]])
    while queue:
        candidates = []
        while queue:
            path = queue.popleft()
            node = path[-1]
            if node == goal:
                return path
            for nb, cost in graph[node]:
                candidates.append((h[nb], path+[nb]))
        candidates.sort(key=lambda x: x[0])
        queue = deque([p for _, p in candidates[:beam_width]])
    return None
def a_star(graph, h, start, goal):
    pq = []
    heapq.heappush(pq, (h[start], 0, start, [start]))
    while pq:
        f, g, node, path = heapq.heappop(pq)
        if node == goal:
            return path, g
        for nb, cost in graph[node]:
            g_new = g + cost
            f_new = g_new + h[nb]
            heapq.heappush(pq, (f_new, g_new, nb, path+[nb]))
    return None, float("inf")
print("\n BEST FIRST SEARCH")
print(best_first2(graph2, heuristic2, 'S', 'G'))
print("\nBEAM SEARCH ")
print(beam_search2(graph2, heuristic2, 'S', 'G', beam_width=2))
print("\n A* SEARCH (Graph 2)")
print(a_star(graph2, heuristic2, 'S', 'G'))



 BEST FIRST SEARCH
Visiting: S
Visiting: C
Visiting: E
Visiting: G
['S', 'C', 'E', 'G']

BEAM SEARCH 
['S', 'C', 'E', 'G']

 A* SEARCH (Graph 2)
(['S', 'A', 'D', 'F', 'G'], 23)


Lab #08

In [32]:
import math
player = 'X'
ai = 'O'
def print_board(board):
    for row in board:
        print(row)
def empty_cells(board):
    return [(i, j) for i in range(3) for j in range(3) if board[i][j] == '_']
def check_winner(board):
    wins = [
        # rows
        [(0,0),(0,1),(0,2)],
        [(1,0),(1,1),(1,2)],
        [(2,0),(2,1),(2,2)],
        # cols
        [(0,0),(1,0),(2,0)],
        [(0,1),(1,1),(2,1)],
        [(0,2),(1,2),(2,2)],
        # diagonals
        [(0,0),(1,1),(2,2)],
        [(0,2),(1,1),(2,0)]
    ]
    for line in wins:
        a,b,c = line
        if board[a[0]][a[1]] == board[b[0]][b[1]] == board[c[0]][c[1]] != '_':
            return board[a[0]][a[1]]
    return None
def minimax(board, depth, isMax):
    winner = check_winner(board)
    if winner == ai:
        return 10 - depth
    if winner == player:
        return depth - 10
    if not empty_cells(board):
        return 0
    if isMax:
        best = -999
        for (i,j) in empty_cells(board):
            board[i][j] = ai
            best = max(best, minimax(board, depth+1, False))
            board[i][j] = '_'
        return best
    else:
        best = 999
        for (i,j) in empty_cells(board):
            board[i][j] = player
            best = min(best, minimax(board, depth+1, True))
            board[i][j] = '_'
        return best
def best_move(board):
    best_val = -999
    move = None
    for (i,j) in empty_cells(board):
        board[i][j] = ai
        value = minimax(board, 0, False)
        board[i][j] = '_'
        if value > best_val:
            best_val = value
            move = (i,j)
    return move
board = [
    ['X','O','X'],
    ['_','O','_'],
    ['_','_','_']
]
print("Current Board:")
print_board(board)
move = best_move(board)
print("\nAI chooses:", move)



Current Board:
['X', 'O', 'X']
['_', 'O', '_']
['_', '_', '_']

AI chooses: (2, 1)


In [33]:
def alphabeta(node, depth, alpha, beta, maximizing_player, tree):
    if node not in tree:  
        return node  
    if maximizing_player:
        value = -999
        for child in tree[node]:
            value = max(value, alphabeta(child, depth + 1, alpha, beta, False, tree))
            alpha = max(alpha, value)
            if beta <= alpha:
                break   
        return value
    else:  
        value = 999
        for child in tree[node]:
            value = min(value, alphabeta(child, depth + 1, alpha, beta, True, tree))
            beta = min(beta, value)
            if beta <= alpha:
                break   
        return value
tree = {
    "A": ["B", "C"],
    "B": ["D", "E"],
    "C": ["F", "G"],
    "D": [4, 2],          
    "E": [-3, -6],        
    "F": [7, 0],          
    "G": [5, 8]           
}
result = alphabeta("A", 0, -999, 999, True, tree)
print("Alpha-Beta Pruning Result =", result)

Alpha-Beta Pruning Result = 7


Lab 09